# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up a specific version of the Java JDK and add the command-line tools to the PATH
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '8'
          # Java distribution. See the list of supported distributions in README file
          distribution: 'adopt'
      # Download Atlassian SDK and install it
      - name: Install Atlassian SDK
        # You may pin to the exact commit or the version.
        # uses: rodrigo-nogues/github-action-install-atlassian-sdk@4b695bc126676bb923332780bdc3c19d1fe6ce8b
        uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      # Compile the plugin
      - run: atlas-package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: 'dotnet-format-for-bitbucket.jar'
          # A file, directory or wildcard pattern that describes what to upload
          path: 'target/dotnet-format-for-bitbucket-*.jar'
